### ISSUE TITLE
There is no way to customize style

### ISSUE THREAD

**Issue by HelmutGoebel** [janizde/WP-Opening-Hours#128]
I don't see any chance to customize style, like font family, font size, font-color etc. Also, there is no chance to customize tablet and mobile settings. When will you implement that?

**Comment by janizde** [comment]
The plugin does not – and will not – provide any options for custom styles, as you can read in the FAQ on WordPress: https://wordpress.org/plugins/wp-opening-hours/#how%20can%20i%20change%20the%20styling%20of%20the%20widgets%20%2F%20shortcodes%3F

The styling of your site should be determined by your theme. (Otherwise any plugin would have to provide these settings, which is rarely the case). It just renders a table or dl. If you need custom styling, you have to do this using custom CSS.

What do you mean by tablet / mobile settings? You can choose among table and list format. The list should fit on mobile. What would you expect from tablet / phone options?

**Comment by HelmutGoebel** [comment]
A reason to switch to another solution asap, since you don't understand the need of the requested features.
