### ISSUE TITLE
Translated to the Spanish and more

### ISSUE THREAD

**Issue by misagues** [janizde/WP-Opening-Hours#14]
Hello Jannik,

I have 100% of the WP Opening Hours translated to the Spanish.

Possibly will have to adjust things. As you see the translations in the plugin in use them I will be adjusting and updating.

I want to merge 1 commit in GitHub

I’ve found some things that do not work well:

I have seen that the months may not be translated, appear in English.

The section settings within the plugin does not appear in wordpress 4.2.2, then cannot be configured or time format or date format.

In the widget overview if you select highlight Current Weekday; skips a day, i.e., highlights the next day to the present.

Thanks.

A greeting.

**Comment by janizde** [comment]
hey @misagues 
the settings have been removed because it now depends on your standard WordPress setting. You can change the date and time formats per widget/shortcode

months are now translated by WordPress core translations so they don't have to be included in the plugin translations.

I will publish beta2 tomorrow please try  to highlight current weekday again (also check your timezone settings then)

thanks for your support!
