### ISSUE TITLE
*suggestions* concatonate closed days and show todays hours.

### ISSUE THREAD

**Issue by JesperStender** [janizde/WP-Opening-Hours#59]
I have to enhancements that I would love to have implemented.
1.) The plugin can search for similar opening days and "concatonate" them into one row - 
but it can't do that with closed days, could this be done? right now I would have to just do it with jquery, but it seems like a php version of this would be both faster and more clean.

2.) shortcode to show only todays opening hours - It is nice to show in the header (or elsewhere) right now i have also done this, by having the op-overview in a hidden div, and select the current day with jquery and insert that tekst into a paragraph that I controle, but a shortcode would be much cleaner and probably also way faster. 

love the plugin, keep up the good work.

**Comment by janizde** [comment]
Hi @JesperStender,
instead of adding two feature requests in one issue please separate them next time so they can be handled independently more easily.

1) This is actually the standard behavior. I have tried this and added a unit test verifying this behavior in 45e40d51c767ef25ec304706cfe34aa9c173506b
Please check again and if it doesn't work please speficy whether you have any Holidays / Irregular Openings set up.

2) I have added this feature to the is-open widget / shortcode and it will be added in 2.1

**Comment by janizde** [comment]
released in v2.1
